# 老王Python学习笔记
> 运行环境：代码编辑器sublime text 3（配置anaconda，python3.5）
## 二、进阶篇

### 进阶篇17-异常处理1.3

#### 3.代码友好，自动处理垃圾，with.

```
#常规方法
f = open('a.txt', 'r')
f.read()
f.close()

# with方法不用关闭文件
with open('a.txt', 'r') as f:
    print(f.read())

'''
进入时，调用对象的__enter__方法
退出时，调用对象的__exit__方法

'''

# 自定义with可以调用的对象
# coding=utf-8

class sth(object):
    """
    自定义with 可调用对象，
    该对象必须有__enter__和__exit__方法，否则抛出异常
    """ 

    def __enter__(self):
        print('I am coming')

    def __exit__(self, type, value, traceback):
        print('I am going')


with sth() as s:
	pass
>>>
I am coming
I am going
```

```

# coding=utf-8

class sth(object):
    """
    with引申
    自定义with 可调用对象，
    该对象必须有__enter__和__exit__方法，否则抛出异常
    """

    def __init__(self, hello):
        self.a = hello

    def __enter__(self):
        print('I am coming')
        return self.a        # __enter__返回值赋值给s

    def __exit__(self, type, value, traceback):
        print('I am going')


with sth('winter is coming') as s:  # __enter__返回值赋值给s
    print(s)

>>>
I am coming
winter is coming
I am going
```

#### 4.自己定义异常？继承exception类。

```
# first example
# coding=utf-8


class myException(Exception):
    """
    自定义异常类
    """

    def __init__(self, error, msg):
        self.args = (error, msg)
        self.error = error
        self.msg = msg


try:
    raise myException('Error', 'amazing')
except Exception as e:
    print(e)
    
>>> ('Error', 'amazing')
```

```
# second example
# coding=utf-8

class myException(Exception):
    """
    定义一个异常类，继承Exception类,
    捕获下面的过程：判断raw_input()输入的字符串长度是否小于5，
    如果小于5，比如输入长度为3则输出:" The input is of length 3,expecting at least 5'
    大于5输出"print success'
    """

    def __init__(self, arg):
        self.arg = arg

    def length(self):
        length = len(self.arg)
        if length < 5:
            return 'The input is of length %d,expecting at least 5' % length
        else:
            return 'print success'


try:
    m = myException('input argument here')
    print(m.length())
except Exception as e:
    print(e)

>>> print success
```

---
### 习题：

 一 编写with操作类Fileinfo()，定义__enter__和__exit__方法。完成功能：

 1.1 在__enter__方法里打开Fileinfo(filename)，并且返回filename对应的内容。如果文件不存在等情况，需要捕获异常。

 1.2 在__enter__方法里记录文件打开的当前日期和文件名。并且把记录的信息保持为log.txt。内容格式："2014-4-5 xxx.txt"

```
# coding=utf-8

import os
import logging


class Fileinfo(object):
    """
    一、编写with操作类Fileinfo()，定义__enter__和__exit__方法。完成功能：
    1.1 在__enter__方法里打开Fileinfo(filename)，并且返回filename对应的内容。如果文件不存在等情况，需要捕获异常。
    1.2 在__enter__方法里记录文件打开的当前日期和文件名。并且把记录的信息保持为log.txt。内容格式："2014-4-5 xxx.txt"
    """

    def __init__(self, filename):
        super(Fileinfo, self).__init__()
        self.filename = filename

    def __enter__(self):
        try:
            f = open(self.filename, 'r')
        except Exception as e:
            return e
        else:
            # 配置根记录器
            logging.basicConfig(
                filename='log.txt', format='%(asctime)s %(message)s', datefmt='%Y-%m-%d', level=logging.INFO)
            log = logging.getLogger('file')       # 创建logger对象
            fn = os.path.split(self.filename)[1]  # 从文件路径提取文件名
            log.info(fn)                          # 记录信息内容
            log = open('log.txt', 'r')            # 打开日志文件
            print('open date and filename:\n%s' % log.read())  # 输出日志文件
            return 'The content of file:\n%s' % f.read()   # 输出目标文件内容

    def __exit__(self, type, value, traceback):
        pass


with Fileinfo(r"C:\Program Files\Sublime Text 3\practice\url.log") as info:
    print(info)
    
>>>
open date and filename:
2017-05-30 url.log
2017-05-30 url.log

The content of file:
ERROR 2017-05-27 23:36:32,865 webpages can't be open: http://www.abc.com
ERROR 2017-05-28 23:12:45,409 webpages can't be open: http://www.abc.com
```
---

 二：用异常方法，处理下面需求：

 info = ['http://xxx.com','http:///xxx.com','http://xxxx.cm'....]任意多的网址

 2.1 定义一个方法get_page(listindex) listindex为下标的索引，类型为整数。 函数调用：任意输入一个整数，返回列表下标对应URL的内容，用try except 分别捕获列表下标越界和url 404 not found 的情况。 

 2.2 用logging模块把404的url，记录到当前目录下的urlog.txt。urlog.txt的格式为：2013-04-05 15:50:03,625 ERROR http://wwwx.com 404 not foud

```
import urllib.request
import logging

info = ['http://www.baidu.com', 'http://www.abc.com', 'http://g.cn']


def get_page(listindex):
    '''
    @listindex为已知列表info下标的索引,类型为整数.
    @函数调用：任意输入一个整数，返回列表下标对应URL的内容.
    用try except 分别捕获列表下标越界和url 404 not found 的情况。
    @异常处理：用logging模块把404的url，记录到当前目录下的urlog.txt。
    urlog.txt的格式为：2013-04-05 15:50:03,625 ERROR http://wwwx.com 404 not foud
    '''
    if not isinstance(listindex, int):
        return '输入参数类型异常'
    try:
        url = urllib.request.urlopen(info[listindex])
    except IndexError as e:   # 记录索引下标越界异常
        return 'IndexError: %s' % e
    except Exception as e:    # 记录网页无法打开异常
        logging.basicConfig(
            filename='urlog.txt', format='%(asctime)s %(levelname)s %(message)s', level=logging.ERROR)
        log = logging.getLogger('url')
        log.error('%s 404 not found' % info[listindex])
        return open('urlog.txt', 'r').read()  # 返回日志文本内容
    else:
        return url.read()
    finally:
        pass


print(get_page(3))
>>> IndexError: list index out of range

print(get_page(1))
>>> 
2017-05-30 23:22:48,284 ERROR http://www.abc.com 404 not found

print(get_page(2))
>>> 正常输出网页内容（字节）
```

---

 三：定义一个方法get_urlcontent(url)。返回url对应内容。

 要求：
 
 1自己定义一个异常类，捕获URL格式不正确的情况，并且用logging模块记录错误信息。

 2 用内置的异常对象捕获url 404 not found的情况。并且print 'url is not found'
 
```
# coding=utf-8
import urllib.request
import urllib.error
import logging


class UrlFmtError(Exception):
    """
    自定义异常类，捕获URL格式不正确的情况，并且用logging模块记录错误信息。
    @存疑
    """

    def __init__(self, url):
        self.url = url

    def urlError(self):
        if not self.url.startswith(('http://', 'https://')):
            logging.basicConfig(
                filename='urlfmt.txt', format='%(asctime)s %(levelname)s %(message)s', level=logging.ERROR)
            log = logging.getLogger('url')
            log.error(self.url)
            print('URL格式不正确')
            # 返回日志文本内容
            return 'Content of log:\n%s' % open('urlfmt.txt', 'r').read()


def get_urlcontent(url):
    '''
    三：定义一个方法get_urlcontent(url)。返回url对应内容。要求：
    1.自己定义一个异常类，捕获URL格式不正确的情况，并且用logging模块记录错误信息。
    2.用内置的异常对象捕获url 404 not found的情况。并且print 'url is not found'
     @存疑：自定义异常类意义不大
    '''
    try:
        u = UrlFmtError(url)
        content = urllib.request.urlopen(url)   # 打开网页
    except ValueError as e:
            return u.urlError()
    except urllib.error.HTTPError as e:
        return 'url is not found'  # 捕获url 404 not found的情况,并print'url is not found'
    except:
        return 'other error'
    else:
        return 'The content:\n%s' % content.read()


print(get_urlcontent('http://www.baidu.com'))
>>> 网页内容（在此省略）

print(get_urlcontent('www.baidu.com'))
>>> URL格式不正确
Content of log:
2017-05-31 13:40:01,205 ERROR www.baidu.com

print(get_urlcontent('http://www.baidu'))
>>> other error
```